### ISSUE TITLE
exe无法运行

### ISSUE THREAD

**Issue by zttawd** [zR00t1/ImageStrike#2]
![image](https://user-images.githubusercontent.com/102441231/194789219-d715af5b-cd0c-40ca-952c-d94ed04c436d.png)
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod04_ctypes.py", line 53, in __init__
  File "ctypes\__init__.py", line 356, in __init__
OSError: [WinError 126] 找不到指定的模块。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyzbar\zbar_library.py", line 58, in load
  File "pyzbar\zbar_library.py", line 54, in load_objects
  File "ctypes\__init__.py", line 434, in LoadLibrary
  File "PyInstaller\loader\pyimod04_ctypes.py", line 55, in __init__
pyimod04_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'libzbar-64.dll'. Most likely this dynlib/dll was not found when the application was frozen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyInstaller\loader\pyimod04_ctypes.py", line 53, in __init__
  File "ctypes\__init__.py", line 356, in __init__
OSError: [WinError 126] 找不到指定的模块。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ImageStrike.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "pyzbar\pyzbar.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "pyzbar\wrapper.py", line 143, in <module>
  File "pyzbar\wrapper.py", line 136, in zbar_function
  File "pyzbar\wrapper.py", line 115, in load_libzbar
  File "pyzbar\zbar_library.py", line 60, in load
  File "pyzbar\zbar_library.py", line 52, in load_objects
  File "pyzbar\zbar_library.py", line 52, in <listcomp>
  File "ctypes\__init__.py", line 434, in LoadLibrary
  File "PyInstaller\loader\pyimod04_ctypes.py", line 55, in __init__
pyimod04_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\ztt\\AppData\\Local\\Temp\\_MEI209802\\pyzbar\\libiconv.dll'. Most likely this dynlib/dll was not found when the application was frozen.

不知道是什么原因

**Comment by zR00t1** [comment]
一般出现这个问题是没有安装Visual C++ 2013运行库，https://www.microsoft.com/zh-cn/download/confirmation.aspx?id=40784

**Comment by zttawd** [comment]
感谢，问题解决了，前面安装错了版本
